package org.marcin1994b.snoozeloo

val ACTION_SHOW_NOTIFICATION = "ACTION_SHOW_NOTIFICATION"
val ACTION_SNOOZE = "ACTION_SNOOZE"
val ACTION_CANCEL = "ACTION_CANCEL"

val EXTRAS_ALARM_ID = "EXTRAS_ALARM_ID"
